import "#/styles/index.css";
import { Instrument_Sans, Roboto_Mono } from 'next/font/google'
import image from "#/public/profile.png";
import Image from "next/image";
import Link from "next/link";
import { IconType } from "react-icons";
import { FaLinkedin, FaGithub, FaEnvelope } from "react-icons/fa";
import styles from "./layout.module.css";
import { Analytics } from "@vercel/analytics/react"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const font = Instrument_Sans({
  subsets: ['latin'],
  display: "swap",
  variable: "--font",
  weight: ['400', '500', '600', '700']
});

const monoFont = Roboto_Mono({
  subsets: ['latin'],
  display: "swap",
  variable: "--font-mono"
});


function ExternalIconLink({ href, icon: Icon }: { href: string, icon: IconType }): JSX.Element {
  return <Link className={styles.social} href={href} target="_blank">
    <Icon className={styles.socialIcon} />
  </Link>
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`container ${font.variable} ${monoFont.variable}`}>
      <head>
        <title>Elijah Cobb</title>
        <link rel="icon" href="https://elijahcobb.com/favicon.svg" />
        <meta property="og:title" content="Elijah Cobb" />
        <meta property="og:description" content="A personal portfolio site for Elijah Cobb." />
        <meta property="og:url" content="https://elijahcobb.com" />
        <meta property="og:image" content="https://elijahcobb.com/og.png" />
        <Analytics />
      </head>
      <body>
        <header className={styles.header}>
          <Link href="/" className={styles.bio}>
            <Image className={styles.headshot} src={image} width={72} alt="elijah headshot" />
            <h1 className={styles.name}>Elijah Cobb</h1>
            <p className={styles.title}>Software Engineer</p>
          </Link>
          <div className={styles.bar}>
            <div className={styles.socials}>
              <ExternalIconLink icon={FaLinkedin} href="http://linkedin.com/in/elijahjcobb" />
              <ExternalIconLink icon={FaGithub} href="https://github.com/elijahjcobb" />
              <ExternalIconLink icon={FaEnvelope} href="mailto:elijah@elijahcobb.com" />
            </div>
          </div>
          <hr className={styles.split} />
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
