import "#/styles/index.css";
import { Instrument_Sans, Roboto_Mono } from 'next/font/google'
import { Header } from "./header";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const font = Instrument_Sans({
  subsets: ['latin'],
  display: "swap",
  variable: "--font",
  weight: ['400', '500', '600', '700']
});

const monoFont = Roboto_Mono({
  subsets: ['latin'],
  display: "swap",
  variable: "--font-mono"
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`container ${font.variable} ${monoFont.variable}`}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
