import "#/styles/index.css";
import { Instrument_Sans, Roboto_Mono } from 'next/font/google'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const font = Instrument_Sans({
  subsets: ['latin'],
  display: "swap",
  variable: "--font",
  weight: ['400', '500', '600', '700']
});

const monoFont = Roboto_Mono({
  subsets: ['latin'],
  display: "swap",
  variable: "--font-mono"
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`container ${font.variable} ${monoFont.variable}`}>
      <head>
        <title>Elijah Cobb</title>
        <link rel="icon" href="/favicon.svg" />
      </head>
      <body>{children}</body>
    </html>
  )
}
